### ISSUE TITLE
go-beanstalk-gin

### ISSUE THREAD

**Issue by sudo-suhas** [awslabs/elastic-beanstalk-docs#53]
Hey, I just authored a repo which demonstrates setting up a webapp using gin in Elastic Beanstalk - [sudo-suhas/go-beanstalk-gin]. 

Do you think it makes sense to add a link to it in the readme for this repo?

If you have any feedback that'd be great too.

[sudo-suhas/go-beanstalk-gin]: https://github.com/sudo-suhas/go-beanstalk-gin

**Comment by dankhen** [comment]
Hi,

I apologize for only getting to this now.
I'd like to give your sample a spin, and if all goes well, happy to add it to our readme. Thanks for contributing!

Some initial observations/requests:
1. Please start your `readme.md` with the dev environment(s) you are assuming for your instructions. E.g. which Linux/Windows OS flavors, which shells, etc.
2. In `create-gin-webapp.md`, you have the comment "If you are on windows, ...". Did you test this sample on Windows? Do all the commands in all steps work *exactly* the same, except for this step? E.g. I would assume you'd need to use backslashes instead of slashes in path names. Maybe you need to add a Windows version of that step?
3. Does the project directory really have to have this particular path - `$GOPATH/src/github.com/<USERNAME>/go-beanstalk-gin`? Can't it be any directory, e.g. something under the user's home directory on Linux? If it's really required to have this path, please mention it and explain why. If not, consider using a simpler path example, so readers don't think it's an actual constraint.
4. In `deploy-to-elastic-beanstalk.md`, please research and solve the whole `.gitignore` issue (between "Oddly enough" and "Maybe a git bug?"). A tutorial should be more prescriptive / definite. E.g. go thru one of our tutorials and see if the same problem exists.
5. In the step "You should be able to see something like this after the application is deployed:" - please specify what the user should do to get this. E.g. use an `eb open` command.

Thanks!

**Comment by sudo-suhas** [comment]
Hey @dankhen Thank you for the through review.

> _Please start your readme.md with the dev environment(s) you are assuming for your instructions. E.g. which Linux/Windows OS flavors, which shells, etc._

I haven't mentioned anything specifically because, for the most part, the commands are not platform dependent. Do you think it okay to mention that the tutorial should be usable on Windows and *nix as most tools and commands are cross platform compatible? I will be mentioning the commands specific to a platform if required.

---

> _In `create-gin-webapp.md`, you have the comment "If you are on windows, ...". Did you test this sample on Windows?_

I am in fact, on Windows and I actually faced an issue with deployment first before coming up with the solution to avoid `CRLF`.

---

> _Do all the commands in all steps work exactly the same, except for this step? E.g. I would assume you'd need to use backslashes instead of slashes in path names. Maybe you need to add a Windows version of the step that creates the project directory?_

You are right about this. I skimmed through all the commands and the only ones which might not work on windows are the one for `mkdir` and `curl`. I'll update the documentation for these.

---

> _Does the project directory really have to have this particular path - `$GOPATH/src/github.com/<USERNAME>/go-beanstalk-gin`? Can't it be any directory, e.g. something under the user's home directory on Linux? If it's really required to have this path, please mention it and explain why._

It is considered a good practice. Here's some relevant documentation:

- https://dave.cheney.net/2014/12/01/five-suggestions-for-setting-up-a-go-project
> In other languages it is quite common to ensure your package has a unique namespace by prefixing it with your company name, say `com.sun.misc.Unsafe`.
If everyone only writes packages corresponding to domains that they control, then there is little possibility of a collision.
>
> In Go, the convention is to include the location of the source code in the package’s import path, ie
> ```
> $GOPATH/src/github.com/golang/glog
> ```

- https://blog.golang.org/organizing-go-code
> #### Choose a good import path (make your package "go get"-able)
> ...
> Sometimes people set `GOPATH` to the root of their source repository and put their packages in directories relative to the repository root, such as `"src/my/package"`. On one hand, this keeps the import paths short (`"my/package"` instead of `"github.com/me/project/my/package"`), but on the other it breaks go get and forces users to re-set their `GOPATH` to use the package. Don't do this.

---

> _In `deploy-to-elastic-beanstalk.md`, please research and solve the whole .gitignore issue (between "Oddly enough" and "Maybe a git bug?")._

I was able to reproduce this behavior multiple times. The only other solution I can think of is to refresh the git index. Do you have any other suggestions?

> In the step "You should be able to see something like this after the application is deployed:" - please specify what the user should do to get this. E.g. use an `eb open` command.

Ok, will do.

---

I'll try to work on these sometime this week.

**Comment by dankhen** [comment]
Hi again!

Yes, I think it should be good to mention that the tutorial should be usable on Windows and *nix, and for full disclosure, add the actual ones you tried it on (e.g.: "I successfully used it on Windows 10... and Ubuntu... .").

BTW, the `curl` command should work on both WIndows and *nix, because the path there is a remote web path, not a local file system path. But it would be good to try.

I don't know about the .gitignore issue; I just have a feeling that it's not special to your tutorial. You can try git or Elastic Beanstalk forums to figure it out. Or, if you can confirm that it's a general problem, just remove it from your tutorial, as it would be irrelevant, and takes away focus from the particular solution you are presenting.

Looking forward to the next commit!

Best,
Danny

**Comment by sudo-suhas** [comment]
Hey @dankhen, I have added a commit([`c3b62e7`](https://github.com/sudo-suhas/go-beanstalk-gin/commit/c3b62e7)) which addresses the feedback you had given. Please take a look.

**Comment by dankhen** [comment]
Looks good! I added it to the readme. Thanks again for the contribution.

**Comment by sudo-suhas** [comment]
Awesome 🎉
